version: '3.7'
services:
  db:
    image: mysql:5.7
    ports: ['3306:3306']
    restart: always
    volumes:
      - './data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jp-grammar
      - MYSQL_USER=jp-grammar
      - MYSQL_PASSWORD=jp-grammar

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

  php:
    build: ./docker/php
    volumes: ['./symfony/:/var/www/symfony:cached']

  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
