version: '3.8'
services:
    db:
        image: mysql:5.7
        ports: [ '3306:3306' ]
        restart: unless-stopped
        volumes:
            - './data/db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD

    adminer:
        image: adminer:4.7
        restart: unless-stopped
        ports:
            - 8080:8080

    php:
        restart: unless-stopped
        build: ./docker/php
        volumes:
            - './:/var/www:cached'
            - /var/www/data/ # exclude data
            - './vendor:/var/www/vendor:cached'
            - './var:/var/www/var'
        environment:
            XDEBUG_CONFIG: client_host=192.168.117.1

    nginx:
        restart: unless-stopped
        build: ./docker/nginx
        ports: [ '80:80' ]
        volumes:
            - './:/var/www:cached'
            - /var/www/data/ # exclude data

    #    rabbitmq:
    #        image: library/rabbitmq:3-management
    #        ports: [ '8081:5672' ]

    mailer:
        restart: unless-stopped
        image: schickling/mailcatcher
        ports: [ '1025:1080' ]
