version: '3.5'
services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - './var/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080


  nginx:
    image: nginx:1.19
    volumes:
      - './api/public:/var/www/api/public:ro'
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80

  php:
    image: php:7.4-fpm
    environment:
      APP_ENV: dev
      ENABLED_EXCEPTION_DEV: 1
    volumes:
      - './api:/var/www/api'
    depends_on:
      - db
