version: '3.8'
services:
    db:
        image: mysql:5.7
        ports: [ '3306:3306' ]
        restart: unless-stopped
        volumes:
            - './data/db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
    db-test:
        image: mysql:5.7
        ports: [ '3307:3306' ]
        restart: unless-stopped
        volumes:
            - './data/db-test:/var/lib/mysql'
        environment:
            - MYSQL_TEST_ROOT_PASSWORD
            - MYSQL_TEST_DATABASE
            - MYSQL_TEST_USER
            - MYSQL_TEST_PASSWORD

    adminer:
        image: adminer:4.7
        restart: unless-stopped
        ports:
            - 8080:8080

    php:
        restart: unless-stopped
        build: ./docker/php
        volumes:
            - type: bind
              source: ./symfony
              target: /var/www/symfony

    nginx:
        restart: unless-stopped
        build: ./docker/nginx
        ports: [ '80:80' ]
        volumes:
            - type: bind
              source: ./symfony
              target: /var/www/symfony

    #    rabbitmq:
    #        image: library/rabbitmq:3-management
    #        ports: [ '8081:5672' ]

    mailer:
        restart: unless-stopped
        image: schickling/mailcatcher
        ports: [ '1025:1080' ]

#volumes:
#    db:
#    db-test:
